etl:
  dataframe1_path: "./data/ECB_FX_USD-base.csv"
  dataframe2_path: "./data/Foreign_Exchange_Rates.csv"
  processed_path: "./data/processed_data.csv"

log:
  log_etl_path: "./log/etl.log"
  log_plot_path: "./log/plots.log"
  log_run_path: "./log/run.log"

plots:
  plot1_path: "./visualizations/plot1.png"
  plot2_path: "./visualizations/plot2.png"
  plot3_path: "./visualizations/plot3.png"